### ISSUE TITLE
Clone-Object -SourceId 1001 = 1001 as it is not a sensor, device or group.

### ISSUE THREAD

**Issue by Zampanno** [lordmilko/PrtgAPI#149] opened 2020-04-30 12:42 UTC
Dear Lord, 

first of all, thank you very much for all the work you put into PrtgAPI

We encountered our first "Error" 
while trying to "Clone-Object" no matter which ID or target we chose, we always get the error 

PS C:\Windows\system32> Get-device *echx* | Clone-Object -SourceId 12345
Clone-Object : Cannot clone object with ID '12345' as it is not a sensor, device or group.

I also tried to use leading zeros "0000012345" to fill it up to ten digits without success .

PS C:\Windows\system32> Get-PrtgClient

Server     : myprtgserver.com
UserName   : Admin
PassHash   : 123456789
Version    : 20.1.57.1745
RetryCount : 1
RetryDelay : 3
LogLevel   : All

Tested with PrtgApi 0.9.7 - 0.9.9 and 0.9.12 

Any idea what i'm doing wrong? 

with kind regards 
Marc

**Comment by lordmilko** [comment] 2020-04-30 12:46
Hi @Zampanno,

This is caused by a bug in PRTG. Update to [PRTG 20.1.57.1786](https://www.paessler.com/prtg/history/stable#20.1.57.1786) or higher

Closing as duplicate of #143

**Closed by lordmilko** 2020-04-30 12:46 UTC
Labels: duplicate
