### ISSUE TITLE
Set-objectproperty DependentObjectId

### ISSUE THREAD

**Issue by mafer0410** [lordmilko/PrtgAPI#86] opened 2019-06-13 16:11 UTC
Hi, from the powershell I try to change the dependency of an object using the set-objectproperty, change the property of the DependentObjectId of a device.
![Captura](https://user-images.githubusercontent.com/51204835/59449029-89b52500-8dc3-11e9-929d-53d04803b640.PNG)
![Uploading Captura.PNG…]()

**Comment by lordmilko** [comment] 2019-06-13 21:18
Please do not create duplicate issues for the same thing

Closing as duplicate of #84

**Closed by lordmilko** 2019-06-13 21:18 UTC

**Comment by mafer0410** [comment] 2019-06-13 21:26
190/5000
Hello, it is not a duplicate, case # 84 is related to the get-objectid.

Case # 86 is related to the set-object-id, I do not know how to use it to
change the DependentObjectId property.

**Comment by mafer0410** [comment] 2019-06-13 21:27
Hello, it is not a duplicate, case # 84 is related to the get-objectid.

Case # 86 is related to the set-object-id, I do not know how to use it to change the DependentObjectId property.

**Comment by lordmilko** [comment] 2019-06-13 21:36
Okay no problem; in that case do not write "I need your help" in unrelated issues then, simply open the new issue.

The code you've written doesn't make any sense

```powershell
get-device -tag *power* | set-objectproperty | select DependentObjectId 2308 | where DependentObjectId -eq 2308
```

* The `Set-ObjectProperty` requires you to specify an *input* object, a property to modify and the value to set the property to. In this code you haven't specified *any* property or value to the `Set-ObjectProperty` cmdlet.
* The `Select-Object` cmdlet takes an *input* object and reduces it to just the columns you specify. You have piped the `Set-ObjectProperty` cmdlet to the `Select-Object` cmdlet - but the `Set-ObjectProperty` cmdlet does not output anything, which means you're not actually specifying any objects you want to select the `DependentObjectId` of. Further to this, you are specifying the arguments `DependentObjectId` and `2308` to the `Select-Object` cmdlet. What does `2308` mean? `Select-Object` doesn't know what to do with that

To change the DependentObjectId to 2001 of all devices that have a tag containing the word `power`, do the following

```powershell
get-device -tag *power* | Set-ObjectProperty DependentObjectId 2001
```

To change the DependentObjectId of all devices that have a tag containing the word `power` *and* have an existing dependency on the object with ID 1001 do the following

```powershell
get-device -tag *power* | where { ($_ | get-objectproperty).DependentObjectId -eq 1001 } | Set-ObjectProperty DependentObjectId 2001
```

**Comment by mafer0410** [comment] 2019-06-13 21:39
Ok, thank you very much, I'm working on a PrtgAPI project and I love the contribution it makes, that's where I'm learning from.

**Comment by mafer0410** [comment] 2019-06-13 21:42
![error](https://user-images.githubusercontent.com/51204835/59469296-af592300-8df1-11e9-9cd1-03a70e8c4725.PNG)
When I try the first option with the set-objectid and select, it asks me to enter the property to be modified, and when I enter dependentobjectid, it gives an error.

**Comment by lordmilko** [comment] 2019-06-13 21:45
Hi @mafer0410,

You have written the same thing you did in the initial post. What you have written does not match what I have written above. You do not need to type `| select` at all, and it is completely illegal to type `where DependentObjectId -eq 2308` as nothing that comes before it has a property called `DependentObjectId`.

Can you please explain exactly what you are trying to do in a sentence and I can advise what to type

Regards,
lordmilko

**Comment by mafer0410** [comment] 2019-06-13 21:48
Yes, I understand, the problem is that the set-objectid command does not recognize the DependentObjectId property, the error appears in all commands and is the only error it gives:
Can not convert value "DependentObjectId" to type "PrtgAPI.ObjectProperty". Error: "Unable to match the identifier name
DependentObjectId to a valid enumerator name.

**Comment by lordmilko** [comment] 2019-06-14 01:14
Ah I see. That indicates that PrtgAPI does not yet support modifying the `DependentObjectId` property.

In order to work around this, you will need to create a set of [raw parameters](https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation#raw-unsupported-1) specifying all of the raw properties that need to be modified.

The following code will set the dependent object ID of all devices that contain a tag containing the word "power" to 1001

```powershell
get-device -tag *power* | Set-ObjectProperty -RawParameters @{
    scheduledependency = 0
    dependencytype_ = 1
    dependency_ = 1001
}
```

**Comment by mafer0410** [comment] 2019-06-14 14:50
Thank you very much for the help, it worked perfectly. I appreciate the
PrtgAPI project and its Wiki that you created.
