### ISSUE TITLE
startIndex cannot be larger than length of string.

### ISSUE THREAD

**Issue by cyberoner1** [lordmilko/PrtgAPI#283] opened 2022-04-08 10:57 UTC
### Describe the bug

When running the script I am getting the error somewhere in the middle, 

```powershell
get-sensorhistory : startIndex cannot be larger than length of string.
Parameter name: startIndex
At C:\Powershell_Scripts\Postgres\Eurogate\history_new.ps1:27 char:114
+ ... lyContinue |get-sensorhistory -Enddate $Enddate -Startdate $Startdate ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-SensorHistory], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : System.ArgumentOutOfRangeException,PrtgAPI.PowerShell.Cmdlets.GetSensorHistory
```

any Idea why=

### Steps to reproduce

```powershell
`$Enddate='2022-03-18 12:00:00'
 $Startdate='2022-03-18 23:59:59'

 #------------Get Data SNMP Traffic-----------------------------------

    get-sensor -tag tableau  -type snmptraffic,snmpdiskfree,snmpcpu,ping -status up -ErrorAction SilentlyContinue |get-sensorhistory -Enddate $Enddate -Startdate $Startdate |  Select-Object -Property DateTime,SensorId,'TrafficIn(volume)','TrafficIn(speed)','TrafficOut(volume)','TrafficOut(speed)',FreeSpace,Total,PacketLoss | Export-csv -Path C:\Powershell_Scripts\Postgres\Eurogate\data\export.csv -Delimiter ";" -NoTypeInformation
```

### What is the output of 'Get-PrtgClient -Diagnostic'?

```powershell
PSVersion      : 5.1.17763.2268
PSEdition      : Desktop
OS             : Microsoft Windows Server 2019 Standard
PrtgAPIVersion : 0.9.17
Culture        : de-DE
CLRVersion     : .NET Framework 4.8 (528049)
PrtgVersion    : 21.3.70.1629
PrtgLanguage   : english.lng
```

**Comment by lordmilko** [comment] 2022-04-08 13:36
Hi @cyberoner1,

After reproducing the error can you please provide the output of `$error[0].Exception.StackTrace`

**Comment by lordmilko** [comment] 2022-04-12 23:35
Thanks @cyberoner1,

Can you also do the following:

First do

```powershell
Set-PrtgClient -LogLevel Response
```
then invite `Get-SensorHistory` again, specifying the `-Verbose` parameter

```powershell
get-sensor -tag tableau  -type snmptraffic,snmpdiskfree,snmpcpu,ping -status up -ErrorAction SilentlyContinue |get-sensorhistory -Enddate $Enddate -Startdate $Startdate -Verbose
```
assuming it still crashes can you please provide a copy of the response that is emitted

**Comment by lordmilko** [comment] 2022-05-03 07:54
Hi @cyberoner1,

Just following up on this, are you able to advise?

**Comment by squintfox** [comment] 2022-08-29 19:42
Hi @lordmilko, I've actually had this same issue for a long time and just happened to see this open issue now.  It happens on maybe 3 or 4 sensors out of around 300, with which ones fail changing week to week (I guess as underlying data changes).  I've attached all the same output requested with a failing sensor.  Hopefully this helps.

Commands:
$current_date = Get-Date
$sensor = Get-Sensor -Id 60010
$sensor | Get-SensorHistory -StartDate $current_date -EndDate $current_date.AddDays(-2) -Average 3600 -Verbose

[output.txt](https://github.com/lordmilko/PrtgAPI/files/9447511/output.txt)

**Comment by lordmilko** [comment] 2022-08-30 03:18
Hi @squintfox,

Thanks for providing these logs. I have pushed a commit which I believe should contain a fix for this issue. Are you able to test PrtgAPI 0.9.18-preview.5 by following the [manual](https://github.com/lordmilko/PrtgAPI/wiki/Installation#manual) installation instructions and advise whether the issue is now resolved?

**Comment by squintfox** [comment] 2022-08-30 15:19
@lordmilko it looks like it's working great.  Thank you.

**Closed** 2022-09-01 04:04 UTC
Labels: alleged-bug
