### ISSUE TITLE
Add-Sensor with params does not work anymore since 23.3.86.1520 (?) "Could not authenticate to PRTG; the specified username and password were invalid.""

### ISSUE THREAD

**Issue by derkveenhof** [lordmilko/PrtgAPI#348] opened 2023-08-11 20:20 UTC
### Describe the bug

Hey,

I think that Add-Sensor does not work anymore since PRTG 23.3.86.1520 .
When i want to add a simple ping sensor to a device, i can get the sensor parameters via New-SensorParameters but Add-Sensor failes. See Screenshot.

I see in the Verbose that the last webrequest towards the api failes. This (get?) webrequest doest not have &username=yourapiuser&passhash=123456789 appended in the uri.. When i copy the uri and append it myself, it works..

Can this be related to a recent CVE that has being patched by Peassler -> https://advisories.ncsc.nl/advisory?id=NCSC-2023-0383 ( im sorry, this is a Dutch CVE reporting website )

![plaatje](https://github.com/lordmilko/PrtgAPI/assets/98036815/03f41e44-7b37-47a9-ba0a-eaa1a3c4ff36)

### Steps to reproduce

```powershell
Import-Module 'PrtgApi' -Verbose
$Credential = Get-Credential
Connect-PrtgServer -Server 'yourhost' -Verbose -Credential $Credential
$Device = Get-Device -Id 4407 -Verbose
$Params = New-SensorParameters -RawType 'ping' -Device $Device -Verbose
$Sensor = Add-Sensor -Destination $Device -Parameters $Params -Verbose
```

### What is the output of 'Get-PrtgClient -Diagnostic'?

```powershell
PSVersion      : 5.1.22621.1778
PSEdition      : Desktop
OS             : Microsoft Windows 11 Enterprise
PrtgAPIVersion : 0.9.18
Culture        : nl-NL
CLRVersion     : 533320
PrtgVersion    : 23.3.86.1520
PrtgLanguage   : english.lng
```

**Comment by lordmilko** [comment] 2023-08-11 23:20
Duplicate of #345

**Closed by lordmilko** 2023-08-11 23:20 UTC
Labels: alleged-bug

**Comment by derkveenhof** [comment] 2023-08-12 08:41
Thanks !! i have to look better :P
