### ISSUE TITLE
HttpDeserializationException sometimes hit when calling GetNotificationTriggersAsync

### ISSUE THREAD

**Issue by paulkva** [lordmilko/PrtgAPI#96] opened 2019-07-03 18:24 UTC
I'm trying to create / update NotificationTriggers on a set of devices and sensors I've created via PrtgAPI. It seems to fail intermittently with a stack trace like the following (I've removed mentions of System.Runtime for brevity):
```
PrtgAPI.HttpDeserializationException
  HResult=0x80131500
  Message=An error occurred while attempting to deserialize property '"_id=': The '"' character, hexadecimal value 0x22, cannot be included in a name..
  Source=PrtgAPI
  StackTrace:
   at PrtgAPI.Request.HtmlParser.GetInputXml(String response, String matchRegex, String nameRegex, Func`2 nameTransformer)
   at PrtgAPI.Request.HtmlParser.GetXml(PrtgResponse response)
   at PrtgAPI.Request.RequestEngine.<ExecuteRequestAsync>d__22.MoveNext()
   at PrtgAPI.PrtgClient.<GetNotificationActionPropertiesAsync>d__573.MoveNext()
   at PrtgAPI.PrtgClient.<UpdateTriggerActionsAsync>d__579.MoveNext()
   at PrtgAPI.PrtgClient.<GetNotificationTriggersInternalAsync>d__577.MoveNext()
   at PrtgAPI.PrtgClient.<GetNotificationTriggersAsync>d__202.MoveNext()
   at PrtgAPI.PrtgClient.<GetNotificationTriggersAsync>d__201.MoveNext()
   at ********.PrtgAlertHelper.<PushNotificationTriggerAsync>d__18.MoveNext() in ********\PrtgAlertHelper.cs:line 114
```
Lines 114-116 in my code are relatively simple:
```C#
var triggers = (await this.Client.GetNotificationTriggersAsync(prtgObject.Id))
                .Where(t => t.Type == TriggerType.State && t.OnNotificationAction?.Name == notificationActionName)
                .ToList();
```
In my latest attempt, the prtgObject is a Device with 5 NotificationTriggers (one of which is inherited). The code works for most other Devices and Sensors, including another Device that's configured identically to the problematic one.

I say "latest attempt" above because the error is unpredictable -- it always fails on the same line of code, but the iteration (i.e. which Device/Sensor I'm updating) changes whenever I change anything. But if my program fails on object X and I run it again with the exact same parameters, I expect it to fail on the same object again. Frustratingly, if I run in debug mode with breakpoints in my code, I haven't gotten it to fail.

Do you have any troubleshooting recommendations aside from downloading PrtgAPI source code and telling Visual Studio to break on exceptions? Otherwise I think that's my next step.

**Comment by lordmilko** [comment] 2019-07-03 22:44
Hi @paulkva,

Can you potentially setup some [request/response](https://github.com/lordmilko/PrtgAPI/wiki/Troubleshooting#c-logging) logging so we can see what's happening underneath? Use `LogLevel.All`. Otherwise, I'd be interested to know if this only happens with the async version of this method

**Comment by lordmilko** [comment] 2019-07-04 00:45
I have looked into this a bit more and it appears you are getting some non-standard HTML in response to a request against `controls/objectdata.htm?id=<id>&objecttype=notification`. Looking at the typical response from this page for a notification action, there is no property called `_id`; not only does your response contain this mysterious property, but the name of the property is completely malformed ('"_id=` instead of `_id` (indicating PrtgAPI's regex parser was tripped up by something)).

By looking at the HTML emitted via the verbose logging mentioned above we can hopefully find the string `_id` in this text and then get an idea as to what we need to do to resolve this issue

**Comment by paulkva** [comment] 2019-07-05 15:42
Fiddler doesn't show any calls to `objectdata.htm` with a malformed response, and neither do the verbose logs. Using the synchronous method (`Client.GetNotificationTriggers()`) works, so I'm guessing there's a bug somewhere in the async version, or perhaps a thread safety issue in PRTG itself.
With the synchronous call, I'm unblocked, although it might be worth leaving this open as a bug.
Thanks for your help!

**Comment by lordmilko** [comment] 2019-07-06 03:43
My immediate thought was either PRTG was emitting a strange new response or PrtgAPI has some sort of race condition (as the asynchronous version works a bit differently to the synchronous one) however unfortunately I haven't been able to replicate this issue

I'm not sure whether you're potentially able to assist in debugging this? The action plan here is simple: 

1. confirm you can compile PrtgAPI from source
2. Remove the NuGet reference to PrtgAPI attach the PrtgAPI.csproj to your solution
3. Set a breakpoint on [this line](https://github.com/lordmilko/PrtgAPI/blob/master/PrtgAPI/Request/HtmlParser.cs#L217)

If you're able to replicate the issue you should easily be able to inspect the `properties`, `props` and `response` members to see where the malformed data came from or what it's related to

**Comment by paulkva** [comment] 2019-07-08 19:39
I'd definitely like to help. I haven't been able to get to it today, but I hope to have time this week. I'll keep you posted. Meanwhile, for what it's worth, it seems like I've needed to change ALL of my notification-related PrtgAPI calls to be synchronous.

**Comment by paulkva** [comment] 2019-07-12 22:30
Found something! An `<input>` field that has an empty string for both its `name` and its `id` attributes in the `response` variable.
`<input class=\"text\"  data-rule-number=\"true\" type=\"text\" name=\"\" id=\"\" autocomplete=\"off\" value=\"1\" >` (that's the escaped value from the Visual Studio debugger)
In both the `props` and `properties` collections, it appears between `summarysubject` and `accessrights`.

I tried pulling the same URL in my browser; it looks like the unnamed field is supposed to be `summinutes`, and that's the only **substantive** difference in the HTML response. (There are other diffs because my personal account has admin access and the API account we use does not, so I can see a bunch of `<option>` tags with other users' names.)

**Comment by lordmilko** [comment] 2019-07-13 06:32
To confirm: you encountered the exception and this was what you found when you inspected the variables of the `GetInputXml` method?

If so, are you potentially able to advise whether you can still replicate this behavior when using a full admin account instead of your API account?

**Comment by lordmilko** [comment] 2019-07-13 06:53
It looks like this is exactly the issue! Upon manually adding this input tag to the list of properties to be parsed in `GetProperties` I get an entry with the name `"_id=`. This makes sense as the regular expression for extracting the `name` expects one or more characters, so having an empty name causes it to skip over to the next quotation mark, which is after `id=`.

The question for me however is *why is PRTG returning a nameless input tag*?

In order to access the Notifications area of PRTG you have to be an administrative user; if you try and retrieve the `objectdata.htm` page of a notification trigger as a non-admin user you'll find that all of the input tags are missing. In your case however, it sounds like whatever user account you were using for this test did have admin level access, as without it you wouldn't have been able to see the `summarysubject` and `accessrights` tags.

Given this appears to me to be an issue with PRTG and the the `summinutes` property corresponds to the `NotificationAction.SummaryPeriod` property which is a nullable integer, I will modify PrtgAPI to disregard any property whose `name` is is empty.

Thanks for your help in debugging this issue!

**Comment by paulkva** [comment] 2019-07-15 14:13
Yes, the code threw the exception in `GetInputXml` and I found the anomaly in local variables. I'm running PRTG 19.2.50.2842.

I agree it appears that PRTG itself is returning incorrect information, but I wonder what's prompting it to do so. The underlying HTTPS calls in PrtgAPI are the same for sync vs async, aren't they? Does PrtgAPI make multiple concurrent calls within the async methods? If so it could be a thread safety issue in PRTG. We've noticed in the past that we can't really parallelize many things in our code without hitting intermittent issues. Now I wonder if it was a similar underlying problem.

**Comment by lordmilko** [comment] 2019-07-15 18:05
Hi @paulkva,

Yes, the async version retrieves the details of all notification triggers in parallel.

In an attempt to stress test PRTG however I wrote a loop to try and retrieve a dozen triggers 100 times and was unable to reproduce the issue.

Interestingly when I tried to increase this loop from 100 to 1000 iterations this caused some persistent performance issues with the PRTG Core that I had to resolve by restarting the service.

What issues have *you* had with parallelism in the past? And has this been using PrtgAPI and its async methods?

**Comment by paulkva** [comment] 2019-07-16 14:00
I suspect the issue is likely related to the number of sensors we have -- more than 10,000 -- which slows down PRTG. I'm guessing parallel API calls on a very large instance are causing some race condition or thread safety issue in their code.

The previous problems we had were similar to what I've described above, and yes we use PrtgAPI's async methods everywhere, but we didn't dig deeply into it at the time because running things sequentially seemed to resolve the issues, and that was sufficient for our needs.

**Comment by lordmilko** [comment] 2019-09-26 00:59
Hi @paulkva,

Please be advised that PrtgAPI 0.9.9 has now been released, which includes a fix for this issue. To update PrtgAPI simply run

```powershell
Update-Package PrtgAPI
```

in the NuGet Package Manager Console. Of course, given that using the non-async version appears to resolve your issue, this may not be required

Regards,
lordmilko

**Closed by lordmilko** 2019-09-26 00:59 UTC
Labels: bug

**Comment by paulkva** [comment] 2019-09-26 18:53
Thanks for the update! We won't upgrade immediately because the synchronous workaround is sufficient for now, but we will definitely plan to upgrade in the near future.
