### ISSUE TITLE
Creating an SNMP Library Sensor with Dynamic Parameters Fails to Resolve

### ISSUE THREAD

**Issue by JustinGrote** [lordmilko/PrtgAPI#98] opened 2019-07-09 00:54 UTC
When creating an SNMP Library with Add-Sensor, it fails to resolve because the created sensors are of type snmpcustomtable, whereas the Resolve function is looking for sensors of type snmplibrary in the filter specifically.

**Workaround**
-Resolve:$false and wait for the sensors separately with get-sensor

**Resolution**
Not sure on this one, I know the need to filter on the specific sensor type, only other option I can think of is capture the existing list of sensors and detect the new sensors as differences.

**Comment by lordmilko** [comment] 2019-07-09 05:29
Duplicate of #47

See also: the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Object-Creation#advanced-creation)

> When resolving added sensors, for accuracy and performance purposes PrtgAPI limits its search to sensors that have the same Type specified in the NewSensorParameters object. If you are creating a sensor with a dynamic sensor type that changes based on exact parameters that are specified (such as snmplibrary) you should set the DynamicType property of the parameters object to true. This can be done at the time of parameter creation via the -DynamicType parameter

**Closed by lordmilko** 2019-07-09 05:29 UTC
Labels: duplicate

**Comment by JustinGrote** [comment] 2019-07-09 06:34
Whoops sorry for the dupe, missed that detail. Thanks!
