### ISSUE TITLE
Set-ChannelProperty setting PercentValue wrong

### ISSUE THREAD

**Issue by Z3nto** [lordmilko/PrtgAPI#63] opened 2019-03-13 10:24 UTC
Hi @lordmilko ,

I've found a strange behaviour, while setting the PercentValue on a traffic channel of the snmptraffic-sensor with powershell. (I've not tested this with c#)
I've tried to set the PercentValue to 1000000:
```powershell
get-sensor -id 27630 | get-channel "traffic in" | Set-ChannelProperty PercentValue 1000000 -verbose
```
Your module seems to send it right as i see in the verbose output:
```powershell
VERBOSE: Set-ChannelProperty: Synchronously executing request https://foo.bar/editsettings?id=27630&ref100percent_0=1000000&percent_0=1&username=foobar&passhash=1234567890
```
But the the value ist 8000 after this.

```powershell
PercentMode           : PercentOfMax
PercentValue          : 8000
```

I've checked the original request, there is an additional parameter "ref100percent_0_factor" which is set to "0,008". So with the request "/editsettings?id=27630&ref100percent_0=1000000&percent_0=1&ref100percent_0_factor=0,008" it's correclty set to 1000000.

Maybe you can check this and change it? Or is there a setting that I've missed?

BR Z3nto

**Comment by lordmilko** [comment] 2019-03-13 10:54
Hi @Z3nto,

Thanks for raising this issue. After looking into this I can confirm that you're right! There is in fact a hidden percent factor contained on every channel that supports percentages. Depending on the type of channel, this can be a totally different value.

As such, I will need to add a new `PercentFactor` property to `Channel` and then utilize this property whenever a user modifies a `PercentValue`. Depending on whether you're modifying sensors with the same `PercentFactor` or not PrtgAPI would need to group the channels you're modifying into separate groups so as many can be modified at once as possible (when executing with `-Batch:$true`). Also troublesome is the fact the channel ID is contained in the middle of this property name, instead of on the end (which breaks the assumptions of multiple internal systems)

There's certainly a little bit of trickiness involved here; I will attempt to implement a resolution to this issue which will be included in PrtgAPI 0.9.6.

In the meantime, if you desperately need to mass modify this value, you can potentially do so using `Set-ObjectProperty` and constructing a set of raw parameters whose names contain the name of the property you're trying to modify as well as the ID of the channel that should be modified (i.e. `percent_0` modifies the percentage of channel ID 0). For more information please see the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation#unsupported-properties-1).

Regards,
lordmilko

**Comment by Z3nto** [comment] 2019-03-13 11:07
Hi @lordmilko ,

thanks for this really quick response.
At the moment I've helped myself out in just deviding my PercentValue by 0,008 before calling set-channelproperty, as I'm just editing the "traffic in" and "traffic out" channel of "snmptraffic" sensors.
If you need a tester for this after you implemented it, just reach out for me.

BR Z3nto

**Comment by lordmilko** [comment] 2019-04-03 10:31
Hi @Z3nto,

Please be advised that PrtgAPI 0.9.6 has now been released, which includes a fix for this issue. For more information other new improvements, please see the [release notes](https://github.com/lordmilko/PrtgAPI/releases/tag/v0.9.6).

As a result of this issue, I was able to resolve a longstanding issue I've been unsure about how to resolve with respect to modifying channel properties: how to make PrtgAPI understand the *unit* of the channel, such that when you modify the limits of a channel whose unit is in *megabytes* doesn't result in you erroneously specifying a limit whose actual value is in *bytes*.

As it turns out, there are in fact *several* hidden *unit factor* properties, for properties including the percent value, spike filters and limits. When modifying a channel property that relies in factors being set, PrtgAPI will now automatically determine the best way to group the channels so as many channels with the same factor can be modified in a single request.

The factor of any given channel can be viewed with the new `Factor` channel property. In practice however you shouldn't need to use this.

Implementing this feature in a way that was appropriate for both C# and PowerShell users was really challenging and required extensive changes to parts of PrtgAPI's internal infrastructure, however has resulted in the elimination big gotcha that can hit users when modifying channel limits.

Thanks for raising this issue!

Regards,
lordmilko

**Closed by lordmilko** 2019-04-03 10:31 UTC
Labels: bug

**Comment by Z3nto** [comment] 2019-04-03 11:10
Hi @lordmilko,

just want to say thanks for your everytime great support and this great tool. <3

BR Z3nto

**Comment by schoenm1** [comment] 2020-04-07 09:26
Hi @lordmilko 
I have excaclty the same problem like @Z3nto 
What I did not get: How can I set the `Factor` in Channel Settings?
`$channel | Set-ChannelProperty "Factor" 1` is not working¨
I have PRTGApi Version 0.9.12

UseCase:
- Depending on the Speed (1 Gbit/s; 10 Gbit/s) i have an Array to set the Link Speed in kbit/s
- After setting link speed, I would like to set on all links (regardless of the linkspeed) the same "%" values as UpperWarningLimit and UpperErrorLimit

**Comment by lordmilko** [comment] 2020-04-07 09:39
Hi @schoenm1,

The `Factor` property of channel objects is a value that is derived from the *unit* of channel. As such, if you want to change the factor, what you actually have to do is change the unit.

Channel unit scaling factors are actually defined on the Settings page of sensors, devices, groups and probes. PrtgAPI [supports](https://github.com/lordmilko/PrtgAPI/blob/master/src/PrtgAPI.PowerShell/PowerShell/Resources/about_ObjectSettings.help.txt) modifying the following unit properties via the `Set-ObjectProperty` cmdlet

```
| Channel Unit Configuration  | Get | Set | Description                                                          |
| --------------------------- | --------- | -------------------------------------------------------------------- |
| InheritChannelUnit          |    Yes    | Whether to inherit Channel Unit Configuration Settings               |
| BandwidthVolumeUnit         |    Yes    | Unit to use for bandwidth volume sensor channels                     |
| BandwidthSpeedUnit          |    Yes    | Unit to use for bandwidth speed sensor channels                      |
| BandwidthTimeUnit           |    Yes    | Time unit to use for bandwidth speed sensor channels                 |
| MemoryUsageUnit             |    Yes    | Unit to use for memory sensor channels                               |
| DiskSizeUnit                |    Yes    | Unit to use for disk size sensor channels                            |
| FileSizeUnit                |    Yes    | Unit to use for file size sensor channels                            |
```

You can also view these properties via the `Get-ObjectProperty` cmdlet

```powershell
C:\> Get-Sensor -Id 1001 | Get-ObjectProperty | select *unit*

InheritChannelUnit  : True
BandwidthVolumeUnit :
BandwidthSpeedUnit  :
BandwidthTimeUnit   :
MemoryUsageUnit     : MByte
DiskSizeUnit        :
FileSizeUnit        :
```

You can see what properties are supported for a given property by typing the name of the parameter and hitting tab, or by just trying something and having the error message tell you what the possible values are

```powershell
Set-ObjectProperty -BandwidthVolumeUnit <tab>
```

Using these two cmdlets you should be able to determine and modify the unit that is in use on the sensor and then potentially modify the value you set to be in the right scaling factor

Please let me know if you have any further questions
