### ISSUE TITLE
Get-Device -Id and Get-Sensor -Id stopped working

### ISSUE THREAD

**Issue by synsof** [lordmilko/PrtgAPI#154] opened 2020-05-28 15:03 UTC
Hi

I have noticed that when running Get-Device -Id or Get-Sensor -Id XXXX i get no information returned.
![image](https://user-images.githubusercontent.com/59028720/83152001-4b477180-a0cb-11ea-93ac-fe8e9314f8f2.png)
![image](https://user-images.githubusercontent.com/59028720/83152067-60240500-a0cb-11ea-987f-43fdeec5ee3f.png)
You can see the following ids are returned when I am querying for warning sensors. However, querying the ids themselves returns nothing
![image](https://user-images.githubusercontent.com/59028720/83157839-0bd05380-a0d2-11ea-83c5-9ba11873e82f.png)

I was on version 0.9.9 of the PrtgAPI when this issue began. I then upgraded to 0.9.13 but no change. The only change i know happened in our environment was that we did upgrade our versions of PRTG. The version of PRTG in our environment is 20.1.57.1745 which we upgraded from  V19.4.54.1506 back in Late March/Early April. I have not used this parameter since before then, so perhaps it was the upgrade. I need Get-Sensor and Get-Device -id specifically to work, since I wrote a script to add devices that used that parameter quite heavily, without it, my script is broken. Other parameters don't seem to have been affected. Get-Device -Host and Get-Device -Name still works, just -id is broken. Your help is appreciated.

**Comment by lordmilko** [comment] 2020-05-28 15:04
Duplicate of #143

**Closed by lordmilko** 2020-05-28 15:04 UTC
Labels: duplicate
