### ISSUE TITLE
PING v2 Sensor and Get-ObjectProperty

### ISSUE THREAD

**Issue by DuRo55** [lordmilko/PrtgAPI#395] opened 2024-06-19 11:55 UTC
### Describe the bug

Get-Property of PING v2 sensor doesnt work:

PS C:\> get-sensor -id 72831 | Get-ObjectProperty
Get-ObjectProperty : Could not deserialize value 'DiscardResult' as it is not a valid member of type 'PrtgAPI.DebugMode'. Could not process XML 
'<injected_writeresult>DiscardResult</injected_writeresult>'.
In Zeile:1 Zeichen:24
+ get-sensor -id 72831 | Get-ObjectProperty
+                        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ObjectProperty], XmlDeserializationException
    + FullyQualifiedErrorId : PrtgAPI.XmlDeserializationException,PrtgAPI.PowerShell.Cmdlets.GetObjectProperty

### Steps to reproduce

```powershell
Just see description please
```

### What is the output of 'Get-PrtgClient -Diagnostic'?

```powershell
PS C:\> get-module prtgapi

ModuleType Version    Name                                ExportedCommands                                                                             
---------- -------    ----                                ----------------                                                                             
Binary     0.9.18     PrtgAPI                             {Add-Device, Add-Group, Add-NotificationTrigger, Add-Sensor...}
```

**Comment by lordmilko** [comment] 2024-06-20 07:07
Hi @DuRo55,

As a workaround you can do `Get-ObjectProperty -Raw`

**Comment by lordmilko** [comment] 2024-06-20 07:08
This is also a duplicate of #392

**Closed by lordmilko** 2024-06-20 07:08 UTC
Labels: alleged-bug
