### ISSUE TITLE
Set-ObjectProperty : PRTG was unable to complete the request. The server responded with the following error: The validation of the data you entered has failed.  Authorization: Required field, not defined. The object has not been changed.

### ISSUE THREAD

**Issue by MikeSouthwell** [lordmilko/PrtgAPI#364] opened 2023-11-05 23:44 UTC
### Describe the bug

Set-ObjectProperty : PRTG was unable to complete the request. The server responded with the following error: The validation of the data you entered has failed. 
Authorization: Required field, not defined. The object has not been changed.

### Steps to reproduce

```powershell
$subjectString = "DEM2-Live-GTS-Backup - Successful!, DEM2-Live-GTS-Backup - Fixed!"

Get-Sensor -Name $backupSensorName | Set-ObjectProperty -RawProperty paessler-microsoft365-mailbox_section-mailbox_group-filter_subject_string_ -RawValue "$subjectString" -Force
```

### What is the output of 'Get-PrtgClient -Diagnostic'?

```powershell
PSVersion      : 5.1.17763.4974
PSEdition      : Desktop
OS             : Microsoft Windows Server 2019 Datacenter
PrtgAPIVersion : 0.9.18
Culture        : en-AU
CLRVersion     : .NET Framework 4.8 (528049)
PrtgVersion    : 23.3.88.1421
PrtgLanguage   : english.lng
```

**Comment by lordmilko** [comment] 2023-11-06 01:33
Duplicate of #345

Please update to PrtgAPI 0.9.19

**Closed by lordmilko** 2023-11-06 01:33 UTC
Labels: duplicate

**Comment by MikeSouthwell** [comment] 2023-11-08 00:10
Hi LordMilko, 

I have updated to 0.9.19, but I am still getting the same error.

Can you please take another look?

PSVersion      : 5.1.17763.4974
PSEdition      : Desktop
OS             : Microsoft Windows Server 2019 Datacenter
PrtgAPIVersion : 0.9.19
Culture        : en-AU
CLRVersion     : .NET Framework 4.8 (528049)
PrtgVersion    : 23.3.88.1421
PrtgLanguage   : english.lng


Set-ObjectProperty : PRTG was unable to complete the request. The server responded with the following error: The validation of the data you entered has failed. Authorization: Required field, not defined. The object has not been changed.
