### ISSUE TITLE
Sensor-Property-Change-Bug

### ISSUE THREAD

**Issue by eric0915** [lordmilko/PrtgAPI#271] opened 2022-02-22 07:45 UTC
### Describe the bug

Hello, when updating the Object-Property ExeFile of a sensor the value for the script in PRTG looks weird:

![image](https://user-images.githubusercontent.com/47006675/155085339-885d82ff-eb58-4b56-845a-5f69c6c8c625.png)

### Steps to reproduce

```powershell
PrtgClient client = new PrtgClient(<URL>, <User>, <Passhash>, AuthMode.PassHash);
client.SetObjectProperty(13104, ObjectProperty.ExeFile, "sensor.exe");
```

### What is the output of 'Get-PrtgClient -Diagnostic'?

```powershell
PrtgAPI v0.9.16
PRTG v21.4.72.1649+
Operating system where the code is run: Windows 10 Pro
Operating system of the PRTG instance: Windows Server 2019 Standard
```

**Comment by lordmilko** [comment] 2022-02-23 21:36
Duplicate of #268

**Closed by lordmilko** 2022-02-23 21:36 UTC
Labels: alleged-bug
