### ISSUE TITLE
Error in Get-NotificationTrigger - Pipeline input

### ISSUE THREAD

**Issue by astapelfeld** [lordmilko/PrtgAPI#144] opened 2020-04-03 07:06 UTC
**Describe the bug**
Get the following error when I store objects in a variable and then try to pass the variable to Get-NotificationTrigger via Pipeline: "Get-NotificationTrigger: Don't know how to extract the pipeline input from a 'System.SZArrayEnumerator' enumerator from type ''.

**Steps to reproduce**

Error:

```powershell
PS /home/user> $p = get-probe                                                                                                                                                                                                      PS /home/user> $p | Get-NotificationTrigger                                                                                                                                                                                        Get-NotificationTrigger: Don't know how to extract the pipeline input from a 'System.SZArrayEnumerator' enumerator from type ''.   
```

This works:

```powershell
PS /home/user> get-probe | Get-NotificationTrigger                                                                                                                                                                                        
```

**What is the output of `Get-PrtgClient -Diagnostic`?**

```powershell
PS /home/user> Get-PrtgClient -Diagnostic

PSVersion      : 7.0.0
PSEdition      : Core
OS             : Linux 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
PrtgAPIVersion : 0.9.12
Culture        : en-US
CLRVersion     : .NETCoreApp,Version=v3.1
PrtgVersion    : 19.4.53.1912
PrtgLanguage   : english.lng
```

**Comment by lordmilko** [comment] 2020-04-03 07:23
Hi @astapelfeld,

This is a duplicate of #136 

Please follow the [manual installation instructions](https://github.com/lordmilko/PrtgAPI/wiki/Installation#manual) to download the latest pre-release build of PrtgAPI 0.9.13 which includes a fix for this issue

Regards,
lordmilko

**Closed by lordmilko** 2020-04-03 07:23 UTC
Labels: duplicate
