### ISSUE TITLE
i want to set/edit ping sensor to be a master Sensor for parent dependency

### ISSUE THREAD

**Issue by jawadelahmar1** [lordmilko/PrtgAPI#285] opened 2022-05-13 16:00 UTC
### What's going on?

i am trying to configure each device to depend on PING Sensor to trigger notifications, if the ping sensor is down , all other sensors will not trigger any emails . this can be achieved on the GUI be selecting this option . is it possible to do this as edit or add in PRTGAPI using PowerShell

![inherit](https://user-images.githubusercontent.com/105509223/168322183-07b118a4-cb10-4e58-b0a2-81cc24b15ef2.png)

thanks

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment] 2022-05-13 22:20
Duplicate of #148

**Closed by lordmilko** 2022-05-13 22:20 UTC
Labels: question
