### ISSUE TITLE
Don't know how to extract the pipeline input from a 'System.ArrayEnumerator' enumerator from type ''.

### ISSUE THREAD

**Issue by Calvfre** [lordmilko/PrtgAPI#252] opened 2021-12-10 21:57 UTC
### Describe the bug

I just started seeing issues with using arrays in the pipeline to PRTGAPI cmdlets
I am not sure exactly which version this issue started with.
I am currently running PowerShell Core 7.2
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

I am seeing the error with Powershell core on Windows, MacOS and Linux
So far I have seen this when piping to: get-device. get-sensor, remove-object

### Steps to reproduce

```powershell
$items = get-device -name something
$items | get-sensor #<< 'System.ArrayEnumerator' enumerator error
$items.foreach({$_}) | get-sensor) # works
get-device -name something | get-sensor # works
$(get-device -name something) | get-sensor #<< 'System.ArrayEnumerator' enumerator error
```

### What is the output of 'Get-PrtgClient -Diagnostic'?

```powershell
Get-PrtgClient -Diagnostic

PSVersion      : 7.2.0
PSEdition      : Core
OS             : Microsoft Windows 10.0.14393
PrtgAPIVersion : 0.9.16
Culture        : en-US
CLRVersion     : .NETCoreApp,Version=v6.0
PrtgVersion    : 21.3.69.1333
PrtgLanguage   : english.lng
```

**Comment by lordmilko** [comment] 2021-12-11 08:50
Hi @Calvfre,

I have pushed a new pre-release version of PrtgAPI which should include a fix for this issue

Are you able to try using the [manual installation instructions](https://github.com/lordmilko/PrtgAPI/wiki/Installation#manual) to run the latest pre-release and advise whether the issue is now resolved?

Regards,
lordmilko

**Comment by Calvfre** [comment] 2021-12-13 14:03
Sure, Let me get my morning started, and I can test shortly.

**Comment by Calvfre** [comment] 2021-12-13 15:38
$(get-group -name something) | get-device
$(get-device -name something) | get-sensor
$testg = get-group -name something
$testg | get-device
$testD = get-device -name something
$testd | get-sensor

Windows: Passed
MacOS: Passed
Linux: Passed

**Closed** 2021-12-13 21:22 UTC
Labels: bug
