### ISSUE TITLE
New PRTG Update possibly introduced new bug.

### ISSUE THREAD

**Issue by codepend** [lordmilko/PrtgAPI#273] opened 2022-02-23 19:08 UTC
### Describe the bug

I am receiving an error calling GetDynamicSensorParametersAsync, it is returning a 401 un-authenticated. I am 99.999% certain this is related to an update to PRTG version 22.1.74.1869. 

Was working previously until update.

PrtgAPI v0.9.16
PRTG v22.1.74.1869+

### Steps to reproduce

```powershell
var result = await client.GetDynamicSensorParametersAsync(device, sensorType);
```

### What is the output of 'Get-PrtgClient -Diagnostic'?

```powershell
Azure Functions, Windows, .net 5.0
```

**Comment by lordmilko** [comment] 2022-02-23 21:37
Duplicate of #268

**Closed** 2022-02-23 21:51 UTC
Labels: duplicate
