### ISSUE TITLE
No output shown if double space in name

### ISSUE THREAD

**Issue by felipgit** [lordmilko/PrtgAPI#150] opened 2020-05-12 07:26 UTC
**Describe the bug**
When trying to get devices or sensors from a probe that has double space in its name, no output is shown, nor errors, just an empty response. I know that the double space in the name was my own fault, but if probe name is `SITE1 - ProbeA  123 (CODE)` instead of `SITE1 - ProbeA 123 (CODE)`, there are no output shown.

**Steps to reproduce**
What happens:
```powershell

Get-Probe "*ProbeA*" | Get-Device

```
Expected:
```powershell

Get-Probe "*ProbeA*" | Get-Device

Name                        Id     Status      Host            Sensors    Group                     Probe
----                        --     ------      ----            -------    -----                     -----
Probe Device                99123  Up          127.0.0.1       2          SITE1 - ProbeA 123 (CO... SITE1 - Probe...
SITE1-Firewall              99124  Up          10.10.10.1      5          Communication             SITE1 - Probe...
SITE1-Server                99125  Up          10.10.10.2      9          Servers                   SITE1 - Probe...
SITE1-Switch                99126  Up          10.10.10.3      2          Equipment                 SITE1 - Probe...

```

**What is the output of `Get-PrtgClient -Diagnostic`?**

```powershell

PSVersion      : 5.1.18362.752
PSEdition      : Desktop
OS             : Microsoft Windows 10 Pro
PrtgAPIVersion : 0.9.12
Culture        : en-US
CLRVersion     : .NET Framework 4.8 (528040)
PrtgVersion    : 19.2.49.2018
PrtgLanguage   : english.lng

```

**Additional context**
Thanks for awesome tools! Also, the fix is to remove the extra space.

**Comment by lordmilko** [comment] 2020-05-12 07:51
Hi @felipgit,

I had a look at this and was able to confirm the behavior you described

I named a probe `SITE1 -  ProbeA 123 (CODE)` (with a double space after the `-`) and confirmed that doing `Get-Probe *ProbeA* | Get-Device` yields no results. If you inspect the name of the probe that is returned from `Get-Probe` however you'll see that in fact the double space is missing from there as well. This is caused by the XML returned from PRTG not being formatted properly (I believe in this case they should have wrapped the fields in `CDATA` rather than raw text, where extraneous whitespace (like double spaces) would automatically be removed.)

Paessler's internal and external API endpoints have a disgraceful number of crazy issues, most of which PrtgAPI works around for you so you don't really notice them. Unfortunately, this issue won't be one of them. And as Paessler are currently working on a new API however, issues like this likely won't be fixed. You can however identify objects with double spaces by using the `Get-ObjectProperty` cmdlet

```powershell
Get-Object | where { ($_|Get-ObjectProperty -raw).name -like "*  *"}
```

Regards,
lordmilko

**Closed by lordmilko** 2020-05-12 07:51 UTC
Labels: issue-external

**Comment by xasz** [comment] 2022-07-06 07:24
Just to let people know.
Problem still exists.
